spring:
  application:
      name: Spring Boot with Flyway and JOOQ
  profiles:
      active: '@spring.profile.active@'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: '@db.url@'
    username: '@db.usr@'
    password: '@db.pwd@'
  jooq:
    sql-dialect: MYSQL
  jackson:
        serialization:
          write_dates_as_timestamps: false
debug: true
flyway:
  locations: filesystem:src/main/resources/migrations